// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TECDatabaseInterface.Models
{

    public partial class EventsContext
    {
        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EventInfo>().HasKey(_event => _event.EventNumber);
        }
    }
}