// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TECDatabaseInterface.Models;

public partial class EventsContext : DbContext
{
    public EventsContext()
    {
    }

    public EventsContext(DbContextOptions<EventsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EventInfo> EventInfos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(Environment.GetEnvironmentVariable("TEC_DATABASE_CONNECTION_EVENTS"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EventInfo>(entity =>
        {
            entity.HasKey(e => e.EventNumber).HasName("PK_EventInfo_EventNumber");

            entity.ToTable("EventInfo");

            entity.Property(e => e.EventNumber).ValueGeneratedNever();
            entity.Property(e => e.EventDescription)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.EventLink).HasColumnType("ntext");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.QuestCompatable).HasDefaultValue(true);
            entity.Property(e => e.UserPings).HasColumnType("ntext");
            entity.Property(e => e.EventLocation)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.EventDate)
                .IsRequired()
                .HasColumnType("datetime");
            entity.Property(e => e.EventEnd)
                .IsRequired()
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}