// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TECDatabaseInterface.Models;

public partial class EventInfo
{
    public int EventNumber { get; set; }

    public string EventName { get; set; }

    public string EventDescription { get; set; }

    public int EventType { get; set; }

    public bool? QuestCompatable { get; set; }

    public string UserPings { get; set; }

    public string EventLink { get; set; }

    public int EventRating { get; set; }

    public DateTime EventDate { get; set; }

    public DateTime EventEnd {  get; set; }

    public string EventLocation { get; set; }
}