// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TECDatabaseInterface.Models;

public partial class UserInfo
{
    public string Username { get; set; }

    public string DiscordUsername { get; set; }

    public string EncryptedPassword { get; set; }

    public string Email { get; set; }

    public int Role { get; set; }

    public bool EmailConfirmed { get; set; }

    public string Pronouns { get; set; }

    public DateTime Birthday { get; set; }

    public int UserID { get; set; }
}