// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TECDatabaseInterface.Models;

public partial class UsersContext : DbContext
{
    public UsersContext()
    {
    }

    public UsersContext(DbContextOptions<UsersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(Environment.GetEnvironmentVariable("TEC_DATABASE_CONNECTION_USERS"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK_UserInfo_UserID");

            entity.ToTable("UserInfo");

            entity.Property(e => e.UserID).ValueGeneratedNever();
            entity.Property(e => e.DiscordUsername).HasColumnType("ntext");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.EncryptedPassword)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.Pronouns)
                .IsRequired()
                .HasColumnType("ntext");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasColumnType("ntext");
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}