// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;

namespace TECDatabaseInterface.Models
{
    public partial class UsersContext
    {

        [DbFunction("GetUsersByID", "dbo")]
        public IQueryable<UserInfo> GetUsersByID(int? UserID)
        {
            return FromExpression(() => GetUsersByID(UserID));
        }

        [DbFunction("GetUsersByEmail", "dbo")]
        public IQueryable<UserInfo> GetUsersByEmail(string Email)
        {
            return FromExpression(() => GetUsersByEmail(Email));
        }

        [DbFunction("GetUsersByUsername", "dbo")]
        public IQueryable<UserInfo> GetUsersByUsername(string Username)
        {
            return FromExpression(() => GetUsersByUsername(Username));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserInfo>().HasKey(user => user.UserID);
        }
    }
}
